feat: реализовал main сервис
EvgeniyFomenko/java-explore-with-me pull request #2
Opened 2023-12-16 12:54 UTC by EvgeniyFomenko

2023-12-17 09:14 UTC, VadimZharkov commented on ewm-main-service/src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS category
А что с форматированием?

2023-12-17 09:15 UTC, VadimZharkov commented on ewm-main-service/pom.xml
> +        <maven.compiler.source>11</maven.compiler.source>
В родительском помнике же уже есть свойства с версиями и кодировкой. Здесь не нужно

2023-12-17 09:19 UTC, VadimZharkov commented on ewm-main-service/src/main/java/ru/practicum/controller/UsersController.java
> +    public List<UserDto> getUsers(@RequestParam(required = false) Integer[] ids, @RequestParam(defaultValue = "0", required = false) int from, @RequestParam(defaultValue = "10", required = false) int
defaultValue = "0" и required = false противоречат друг другу, т.к. значение будет всегда

2023-12-17 09:22 UTC, VadimZharkov reviewed
Лучше пакет controller разбить на три admin, priv и pub для лучшей структуры проекта

2023-12-17 09:26 UTC, VadimZharkov commented on ewm-main-service/src/main/java/ru/practicum/exception/ControllerException.java
> +}
Добавить Throwable в INTERNAL_SERVER_ERROR

2023-12-17 09:29 UTC, VadimZharkov commented on ewm-main-service/src/main/java/ru/practicum/dto/event/UpdateEventAdminRequest.java
> +public class UpdateEventAdminRequest {
Нужно использовать валидацию, желательно через аннотации

2023-12-17 09:31 UTC, VadimZharkov commented on ewm-main-service/src/main/java/ru/practicum/dto/event/NewEventDto.java
> +public class NewEventDto {
Тоже валидация нужна

2023-12-17 09:36 UTC, VadimZharkov commented on ewm-main-service/src/main/java/ru/practicum/service/compilation/CompilationServiceImpl.java
> +        List<Event> eventList = compilation.getEvent().stream().map(e -> eventRepository.findById(e.getId()).get()).collect(Collectors.toList());
Нужно переделать без цикла/стрима, желательно одним запросом

2023-12-17 09:40 UTC, VadimZharkov commented on ewm-main-service/src/main/java/ru/practicum/service/event/EventServiceImpl.java
> +        if (!event.getEventDate().isAfter(LocalDateTime.now().plusHours(2))) {
Все что выше можно в принципе аннотациями сделать

2023-12-17 09:42 UTC, VadimZharkov commented on ewm-main-service/src/main/java/ru/practicum/service/event/EventServiceImpl.java
> +        } else if (State.PUBLISH_EVENT.toString().equals(updateEventAdminRequest.getStateAction())) {
Лучше не строки сравнивать а перевести в перечислимое и сравнивать уже его значения.

2023-12-17 09:44 UTC, VadimZharkov commented on ewm-main-service/src/main/java/ru/practicum/service/users/UserServiceImpl.java
> +        if (Objects.isNull(user.getEmail()) || user.getEmail().isBlank() || user.getEmail().isEmpty()) {
Тоже можно все сделать аннотациями

2023-12-17 09:45 UTC, VadimZharkov commented on ewm-stats-service/stats-client/pom.xml
> +        <maven.compiler.source>11</maven.compiler.source>
Это есть в родительском pom

2023-12-17 09:48 UTC, VadimZharkov commented on ewm-stats-service/stats-server/src/main/java/ru/practicum/exception/ExceptionController.java
> +}
IllegalArgumentException может тоже возникнуть

2023-12-17 09:52 UTC, VadimZharkov requested changes
Можно улучшить

2023-12-17 09:57 UTC, EvgeniyFomenko commented on ewm-main-service/src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS category
Авто форматирование почему то так работает )

2023-12-17 09:57 UTC, EvgeniyFomenko commented on ewm-main-service/pom.xml
> +        <maven.compiler.source>11</maven.compiler.source>
Да у меня проблемы были со сборкой пришлось разные варианты пробовать)

2023-12-17 10:06 UTC, EvgeniyFomenko commented on ewm-main-service/src/main/java/ru/practicum/exception/ControllerException.java
> +}
Вот это не понял, можно по подробнее

2023-12-17 14:37 UTC, EvgeniyFomenko commented on ewm-main-service/src/main/java/ru/practicum/controller/UsersController.java
> +    public List<UserDto> getUsers(@RequestParam(required = false) Integer[] ids, @RequestParam(defaultValue = "0", required = false) int from, @RequestParam(defaultValue = "10", required = false) int
<img width="1111" alt="image" src="https://github.com/EvgeniyFomenko/java-explore-with-me/assets/49038282/0bf5f065-01ee-47ec-adc6-72033058e1b1">

2023-12-18 09:11 UTC, EvgeniyFomenko commented on ewm-main-service/src/main/java/ru/practicum/controller/UsersController.java
> +    public List<UserDto> getUsers(@RequestParam(required = false) Integer[] ids, @RequestParam(defaultValue = "0", required = false) int from, @RequestParam(defaultValue = "10", required = false) int
удалил сначала defaultValue = "0"  получил ошибку выше а потом решил удалить только  required = false то всё получилось

2023-12-18 12:21 UTC, VadimZharkov commented on ewm-main-service/src/main/java/ru/practicum/exception/ControllerException.java
> +}
```
@ExceptionHandler
@ResponseStatus(HttpStatus.INTERNAL_SERVER_ERROR)
	public ErrorResponse handleThrowable(final Throwable e) {
		log.info("500 {}", e.getMessage(), e);
		return new ErrorResponse(e.getMessage());
	}

```

2023-12-18 12:25 UTC, VadimZharkov approved these changes

2023-12-18 12:36 UTC, merged